model = dict(
    type='PSGTr',
    backbone=dict(type='ResNet',
                  depth=50,
                  num_stages=4,
                  out_indices=(0, 1, 2, 3),
                  frozen_stages=1,
                  norm_cfg=dict(type='BN', requires_grad=False),
                  norm_eval=True,
                  style='pytorch',
                  init_cfg=dict(type='Pretrained',
                                checkpoint='torchvision://resnet50')),
    bbox_head=dict(
        type='SGTRHead',
        num_classes=80,
        num_relations=117,
        in_channels=2048,
        transformer=dict(
            type='Transformer',
            encoder=dict(type='DetrTransformerEncoder',
                         num_layers=6,
                         transformerlayers=dict(
                             type='BaseTransformerLayer',
                             attn_cfgs=[
                                 dict(type='MultiheadAttention',
                                      embed_dims=256,
                                      num_heads=8,
                                      dropout=0.1)
                             ],
                             feedforward_channels=2048,
                             ffn_dropout=0.1,
                             operation_order=('self_attn', 'norm', 'ffn',
                                              'norm'))),
            decoder=dict(type='DetrTransformerDecoder',
                          return_intermediate=True,
                          num_layers=6,
                          transformerlayers=dict(
                              type='DetrTransformerDecoderLayer',
                              attn_cfgs=dict(type='MultiheadAttention',
                                             embed_dims=256,
                                             num_heads=8,
                                             dropout=0.1),
                              feedforward_channels=2048,
                              ffn_dropout=0.1,
                              operation_order=('self_attn', 'norm',
                                               'cross_attn', 'norm', 'ffn',
                                               'norm'))),
        ),
        predicate_node_generator=dict(
            type='Predicate_Node_Generator',
            num_classes=80,
            rel_encoder=dict(type='DetrTransformerEncoder',
                         num_layers=3,
                         transformerlayers=dict(
                             type='BaseTransformerLayer',
                             attn_cfgs=[
                                 dict(type='MultiheadAttention',
                                      embed_dims=256,
                                      num_heads=8,
                                      dropout=0.1)
                             ],
                             feedforward_channels=2048,
                             ffn_dropout=0.1,
                             operation_order=('self_attn', 'norm', 'ffn',
                                              'norm'))),
            rel_decoder=dict(type='DetrTransformerDecoder',
                          return_intermediate=True,
                          num_layers=3,
                          transformerlayers=dict(
                              type='DetrTransformerDecoderLayer',
                              attn_cfgs=dict(type='MultiheadAttention',
                                             embed_dims=256,
                                             num_heads=8,
                                             dropout=0.1),
                              feedforward_channels=2048,
                              ffn_dropout=0.1,
                              operation_order=('self_attn', 'norm',
                                               'cross_attn', 'norm', 'ffn',
                                               'norm'))),
            rel_q_gen_decoder=dict(type='DetrTransformerDecoder',
                          return_intermediate=True,
                          num_layers=1,
                          transformerlayers=dict(
                              type='DetrTransformerDecoderLayer',
                              attn_cfgs=dict(type='MultiheadAttention',
                                             embed_dims=256,
                                             num_heads=8,
                                             dropout=0.1),
                              feedforward_channels=2048,
                              ffn_dropout=0.1,
                              operation_order=('self_attn', 'norm',
                                               'cross_attn', 'norm', 'ffn',
                                               'norm'))),
            entities_aware_decoder=dict(type='DetrTransformerDecoder',
                          return_intermediate=True,
                          num_layers=3,
                          transformerlayers=dict(
                              type='DetrTransformerDecoderLayer',
                              attn_cfgs=dict(type='MultiheadAttention',
                                             embed_dims=256,
                                             num_heads=8,
                                             dropout=0.1),
                              feedforward_channels=2048,
                              ffn_dropout=0.1,
                              operation_order=('self_attn', 'norm',
                                               'cross_attn', 'norm', 'ffn',
                                               'norm'))),                            
        ),
        entities_aware_indexing_head=dict(
            type="EntitiesIndexingHeadRuleBased",
            embed_dims=256,
            num_classes=80,
        ),
        indexing_module_type="rule_base",
        positional_encoding=dict(type='SinePositionalEncoding',
                                 num_feats=128,
                                 normalize=True),
        rel_loss_cls=dict(type='CrossEntropyLoss',
                          use_sigmoid=False,
                          loss_weight=4.0,
                          class_weight=1.0),
        sub_loss_cls=dict(type='CrossEntropyLoss',
                                     use_sigmoid=False,
                                     loss_weight=4.0,
                                     class_weight=1.0),
        sub_loss_bbox=dict(type='L1Loss', loss_weight=5.0),
        sub_loss_iou=dict(type='GIoULoss', loss_weight=2.0),
        sub_focal_loss=dict(type='BCEFocalLoss', loss_weight=2.0),
        sub_dice_loss=dict(type='psgtrDiceLoss', loss_weight=2.0),
        obj_loss_cls=dict(type='CrossEntropyLoss',
                            use_sigmoid=False,
                            loss_weight=4.0,
                            class_weight=1.0),
        obj_loss_bbox=dict(type='L1Loss', loss_weight=5.0),
        obj_loss_iou=dict(type='GIoULoss', loss_weight=2.0),
        obj_focal_loss=dict(type='BCEFocalLoss', loss_weight=2.0),
        obj_dice_loss=dict(type='psgtrDiceLoss', loss_weight=2.0),
        loss_rel_vec=dict(type='L1Loss', loss_weight=2.0),
        loss_cls=dict(type='CrossEntropyLoss',
                      use_sigmoid=False,
                      loss_weight=4.0,
                      class_weight=1.0),
        loss_bbox=dict(type='L1Loss', loss_weight=3.0),
        loss_iou=dict(type='GIoULoss', loss_weight=2.0),
        focal_loss=dict(type='BCEFocalLoss', loss_weight=1.0),
        dice_loss=dict(type='psgtrDiceLoss', loss_weight=1.0)),
    # training and testing settings
    train_cfg=dict(id_assigner=dict(type='IdMatcher',
                                    sub_id_cost=dict(type='ClassificationCost',
                                                     weight=1.),
                                    obj_id_cost=dict(type='ClassificationCost',
                                                     weight=1.),
                                    r_cls_cost=dict(type='ClassificationCost',
                                                    weight=1.)),
                   bbox_assigner=dict(type='HungarianAssigner',
                                      cls_cost=dict(type='ClassificationCost',
                                                    weight=4.0),
                                      reg_cost=dict(type='BBoxL1Cost',
                                                    weight=3.0),
                                      iou_cost=dict(type='IoUCost',
                                                    iou_mode='giou',
                                                    weight=2.0)),
                    rel_assigner=dict(type='RelHungarianMatcher',
                                cost_rel_class = dict(type='ClassificationCost', weight=4.0),
                                cost_rel_vec = dict(type='BBoxL1Cost', weight=2.0),
                                cost_class = dict(type='ClassificationCost', weight=4.0),
                                cost_bbox = dict(type='BBoxL1Cost', weight=5.0),
                                cost_giou = dict(type='IoUCost', iou_mode='giou', weight=2.0),
                                cost_indexing = dict(type='IndexCost', weight=1.0),
                                cost_foreground_ent = 0.3,
                                num_entities_pairing_train = 20,
                                num_entities_pairing = 3,
                                num_matching_per_gt = 1,),
                    ),
    test_cfg=dict(max_per_img=100))
